local M = {}

function M.setup(c)
  local hl = vim.api.nvim_set_hl

  hl(0, "NeoTreeNormal", { fg = c.text, bg = c.mantle })
  hl(0, "NeoTreeNormalNC", { fg = c.text, bg = c.mantle })
  hl(0, "NeoTreeWinSeparator", { fg = c.mantle, bg = c.mantle })
  hl(0, "NeoTreeEndOfBuffer", { fg = c.mantle, bg = c.mantle })
  hl(0, "NeoTreeRootName", { fg = c.pink, bold = true })
  hl(0, "NeoTreeDirectoryName", { fg = c.blue })
  hl(0, "NeoTreeDirectoryIcon", { fg = c.blue })
  hl(0, "NeoTreeSymbolicLinkTarget", { fg = c.teal })
  hl(0, "NeoTreeFileName", { fg = c.text })
  hl(0, "NeoTreeFileIcon", { fg = c.text })
  hl(0, "NeoTreeFileNameOpened", { fg = c.pink })
  hl(0, "NeoTreeIndentMarker", { fg = c.surface2 })
  hl(0, "NeoTreeExpander", { fg = c.subtext0 })
  hl(0, "NeoTreeModified", { fg = c.peach })
  hl(0, "NeoTreeGitAdded", { fg = c.green })
  hl(0, "NeoTreeGitConflict", { fg = c.peach })
  hl(0, "NeoTreeGitDeleted", { fg = c.red })
  hl(0, "NeoTreeGitIgnored", { fg = c.overlay2 })
  hl(0, "NeoTreeGitModified", { fg = c.peach })
  hl(0, "NeoTreeGitRenamed", { fg = c.teal })
  hl(0, "NeoTreeGitStaged", { fg = c.green })
  hl(0, "NeoTreeGitUnstaged", { fg = c.peach })
  hl(0, "NeoTreeGitUntracked", { fg = c.green })
  hl(0, "NeoTreeTitleBar", { fg = c.base, bg = c.pink, bold = true })
  hl(0, "NeoTreeFloatBorder", { fg = c.surface2, bg = c.surface0 })
  hl(0, "NeoTreeFloatTitle", { fg = c.pink, bg = c.surface0, bold = true })
  hl(0, "NeoTreeCursorLine", { bg = c.surface1 })
  hl(0, "NeoTreeDimText", { fg = c.overlay2 })
  hl(0, "NeoTreeDotfile", { fg = c.overlay2 })
  hl(0, "NeoTreeMessage", { fg = c.subtext0, italic = true })
  hl(0, "NeoTreeFadeText1", { fg = c.overlay1 })
  hl(0, "NeoTreeFadeText2", { fg = c.overlay0 })
  hl(0, "NeoTreeTabActive", { fg = c.text, bg = c.surface1, bold = true })
  hl(0, "NeoTreeTabInactive", { fg = c.subtext0, bg = c.mantle })
  hl(0, "NeoTreeTabSeparatorActive", { fg = c.pink, bg = c.surface1 })
  hl(0, "NeoTreeTabSeparatorInactive", { fg = c.mantle, bg = c.mantle })
  hl(0, "NeoTreeFilterTerm", { fg = c.pink, bold = true })
  hl(0, "NeoTreeBufferNumber", { fg = c.subtext0 })
end

return M
