local M = {}

function M.setup(c, o)
  local hl = vim.api.nvim_set_hl
  local bg = o.transparent_background and c.none or c.surface0

  hl(0, "TelescopeNormal", { fg = c.text, bg = bg })
  hl(0, "TelescopeBorder", { fg = c.surface2, bg = bg })
  hl(0, "TelescopeTitle", { fg = c.pink, bold = true })
  hl(0, "TelescopePromptNormal", { fg = c.text, bg = c.surface1 })
  hl(0, "TelescopePromptBorder", { fg = c.surface1, bg = c.surface1 })
  hl(0, "TelescopePromptTitle", { fg = c.base, bg = c.pink, bold = true })
  hl(0, "TelescopePromptPrefix", { fg = c.pink })
  hl(0, "TelescopePromptCounter", { fg = c.subtext0 })
  hl(0, "TelescopeResultsNormal", { fg = c.text, bg = bg })
  hl(0, "TelescopeResultsBorder", { fg = c.surface2, bg = bg })
  hl(0, "TelescopeResultsTitle", { fg = c.pink })
  hl(0, "TelescopePreviewNormal", { fg = c.text, bg = bg })
  hl(0, "TelescopePreviewBorder", { fg = c.surface2, bg = bg })
  hl(0, "TelescopePreviewTitle", { fg = c.pink })
  hl(0, "TelescopeSelection", { fg = c.text, bg = c.surface2 })
  hl(0, "TelescopeSelectionCaret", { fg = c.pink, bg = c.surface2 })
  hl(0, "TelescopeMultiSelection", { fg = c.teal, bg = c.surface2 })
  hl(0, "TelescopeMultiIcon", { fg = c.teal })
  hl(0, "TelescopeMatching", { fg = c.pink, bold = true })
  hl(0, "TelescopePreviewLine", { bg = c.surface1 })
  hl(0, "TelescopePreviewMatch", { fg = c.pink, bold = true })
  hl(0, "TelescopePreviewPipe", { fg = c.subtext0 })
  hl(0, "TelescopePreviewCharDev", { fg = c.peach })
  hl(0, "TelescopePreviewDirectory", { fg = c.blue })
  hl(0, "TelescopePreviewBlock", { fg = c.peach })
  hl(0, "TelescopePreviewLink", { fg = c.teal })
  hl(0, "TelescopePreviewSocket", { fg = c.pink })
  hl(0, "TelescopePreviewRead", { fg = c.green })
  hl(0, "TelescopePreviewWrite", { fg = c.peach })
  hl(0, "TelescopePreviewExecute", { fg = c.red })
  hl(0, "TelescopePreviewHyphen", { fg = c.subtext0 })
  hl(0, "TelescopePreviewSticky", { fg = c.peach })
  hl(0, "TelescopePreviewSize", { fg = c.green })
  hl(0, "TelescopePreviewUser", { fg = c.blue })
  hl(0, "TelescopePreviewGroup", { fg = c.blue })
  hl(0, "TelescopePreviewDate", { fg = c.subtext0 })
  hl(0, "TelescopePreviewMessage", { fg = c.text })
  hl(0, "TelescopePreviewMessageFillchar", { fg = c.subtext0 })
  hl(0, "TelescopeResultsClass", { fg = c.teal })
  hl(0, "TelescopeResultsConstant", { fg = c.peach })
  hl(0, "TelescopeResultsField", { fg = c.text })
  hl(0, "TelescopeResultsFunction", { fg = c.blue })
  hl(0, "TelescopeResultsMethod", { fg = c.blue })
  hl(0, "TelescopeResultsOperator", { fg = c.blue })
  hl(0, "TelescopeResultsStruct", { fg = c.teal })
  hl(0, "TelescopeResultsVariable", { fg = c.text })
  hl(0, "TelescopeResultsLineNr", { fg = c.overlay1 })
  hl(0, "TelescopeResultsIdentifier", { fg = c.text })
  hl(0, "TelescopeResultsNumber", { fg = c.peach })
  hl(0, "TelescopeResultsComment", { fg = c.overlay2 })
  hl(0, "TelescopeResultsSpecialComment", { fg = c.overlay2 })
  hl(0, "TelescopeResultsDiffChange", { fg = c.peach })
  hl(0, "TelescopeResultsDiffAdd", { fg = c.green })
  hl(0, "TelescopeResultsDiffDelete", { fg = c.red })
  hl(0, "TelescopeResultsDiffUntracked", { fg = c.overlay2 })
end

return M
